### ISSUE TITLE
Multiple Modules of the same type?

### ISSUE THREAD

**Issue by starfishmod** [SpektroAudio/Patchbook#3]
If in your examples you had 2 Metropolis modules would the idea be that you'd say "Metropolis 1" and "Metropolis 2"?

Or would it be better to have a section that describes a modules characteristics (or a library for other users to build upon) to say to "Module1" is a type of Metropolis with these characteristics that are different than the "default" settings; and "Module2" is also a type of Metropolis with these values that are different from "default"?

**Comment by icaroferre** [comment]
My suggestion is to use the first option and append a number to module name (so Metropolis 1 and Metropolis 2).
You could then describe the different parameters for the 2 modules like:
* Metropolis 1: INTEXT = c_InT | BPM = 140 | SWING = 50 | do = 1 |
* Metropolis 2: INTEXT = c_EXT | do = 1 | di = 2
(In this example, Metropolis 2 would be clocked by Metropolis 1)
