### ISSUE TITLE
Tuning Oscillators

### ISSUE THREAD

**Issue by robgmsn** [SpektroAudio/Patchbook#4]
Great work, really interested to see where this goes 👍 

If you have a patch with two or three VCOs, how would you denote them being tuned or detuned? Or tuned an octave up or down?

**Comment by robgmsn** [comment]
Also with a VCO you might have a Coarse and Fine knob, but I guess you're just setting the Freq.
So maybe you would have...

* VCO 1: Freq = 65.41 Hz

* VCO 2: Freq = 65 Hz

* VCO 3: Freq = 98 Hz

**Comment by icaroferre** [comment]
That's exactly what I was thinking. You'd also have the option to write the knob position as a percentage but I guess that wouldn't be too reliable in that case.

**Comment by robgmsn** [comment]
Yeah, that makes sense :)
