### ISSUE TITLE
[Suggestion] Colors coding

### ISSUE THREAD

**Issue by cristianvogel** [SpektroAudio/Patchbook#9]
I found that because graphviz is often merging edges (cables) into the same line , it can be difficult to see which signal is being patched where at the end. 

I found that I can untangle this easiest using the color attribute (and svg text color labels) in graphviz, but perhaps it could be useful to have it the markup too? 

- Metropolis (Pitch) p> Braids (1v/oct) :blue

**Comment by icaroferre** [comment]
Yeah, I agree this would be a nice addition. I've been thinking about adding option arguments to the connections and comments which could be used for specific problems like that.
So, instead of :blue, it'd be something like:
Metropolis (Pitch) p> Braids (1v/oct) [color = "blue"]

**Comment by icaroferre** [comment]
Added support for colors as extra arguments: https://github.com/SpektroAudio/Patchbook/commit/89ffe26b3a5ac3270daeef9b3e6edf01dbced020
